// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWIRs3LDnXOPFQDfc7sCJy_b6adLlJPno',
    appId: '1:517458835790:web:5a4a501bfc401bda34461f',
    messagingSenderId: '517458835790',
    projectId: 'ahmedfoued-18f7d',
    authDomain: 'ahmedfoued-18f7d.firebaseapp.com',
    storageBucket: 'ahmedfoued-18f7d.appspot.com',
    measurementId: 'G-4NGT0DLZCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkE99mXL7arrBQ4ur8O_wE4qnm1dmqJQE',
    appId: '1:517458835790:android:a311bd19475415d634461f',
    messagingSenderId: '517458835790',
    projectId: 'ahmedfoued-18f7d',
    storageBucket: 'ahmedfoued-18f7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOfkQ6VSc7--rpPL09KpFDkCXpKvXWj9I',
    appId: '1:517458835790:ios:ff7af3590f20921234461f',
    messagingSenderId: '517458835790',
    projectId: 'ahmedfoued-18f7d',
    storageBucket: 'ahmedfoued-18f7d.appspot.com',
    iosBundleId: 'com.example.ahmedfoued',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOfkQ6VSc7--rpPL09KpFDkCXpKvXWj9I',
    appId: '1:517458835790:ios:5bcd7400e964e1be34461f',
    messagingSenderId: '517458835790',
    projectId: 'ahmedfoued-18f7d',
    storageBucket: 'ahmedfoued-18f7d.appspot.com',
    iosBundleId: 'com.example.ahmedfoued.RunnerTests',
  );
}
